### PR TITLE
SSH Tunnel and Logger specification

### PR DESCRIPTION
**Pull request by ErikZigo**
- fixed creating ssh tunnel
- fixed tests for ssh tunnel

- logger specification on application create (bc-break)

### CODE REVIEW

**Comment by MiroCillik** [comment]
A co ten failnuty test? :)

**Comment by ErikZigo** [comment]
To fixnu.
Ty jsi udelal svoji upravu primo do masteru bez ve stejnou dobu, jako ja poslal PR. Takze to musim jeste pomergovat k sobe do branche a finout

**Comment by ErikZigo** [comment]
@MiroCillik uz

**Comment by MiroCillik** [comment]
supr

**Pull request merged**
